FROM jenkins/jenkins:lts
RUN /usr/local/bin/install-plugins.sh docker-slaves github-branch-source:1.8 cloudfoundry google-deployment-manager google-login google-cloudbuild docker-swarm aws-java-sdk docker-java-api
